services:
  backend:
    build: ./backend
    container_name: grade-pilot-backend
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/sessions:/app/sessions
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: grade-pilot-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
